name: flatnotes
services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - FLATNOTES_AUTH_TYPE=password
      - FLATNOTES_USERNAME=charlie
      - FLATNOTES_PASSWORD=charlie
      - FLATNOTES_SECRET_KEY=aLongRandomSecretKey123
    volumes:
      - /DATA/AppData/$AppID/data:/data
    ports:
      - 8090:8080

x-casaos:
  architectures:
    - amd64
    - arm64
  main: flatnotes
  title:
    en_us: Flatnotes
  tagline:
    en_us: A self-hosted, database-less note-taking web app.
  description:
    en_us: A distraction-free note-taking app that utilizes a flat folder of markdown files for storage. No database, just your files.
  developer: Dullage
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/flatnotes.png
  category: Charlie
  port_map: "8090"
