name: baikal
services:
  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    restart: always
    ports:
      - "8001:80"
    volumes:
      - /DATA/AppData/baikal/config:/var/www/baikal/config
      - /DATA/AppData/baikal/data:/var/www/baikal/Specific
    x-casaos:
      ports:
        - container: "8001"
          description:
            en_us: "Web Interface"
      volumes:
        - container: /var/www/baikal/config
          description:
            en_us: "Configuration"
        - container: /var/www/baikal/Specific
          description:
            en_us: "Database and User Data"

x-casaos:
  architectures:
    - amd64
    - arm64
  main: baikal
  author: ckulka
  category: Charlie
  description:
    en_us: "Baïkal is a lightweight CalDAV+CardDAV server. It offers an extensive web interface with easy management of users, address books and calendars."
  developer: Net Gusto
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/baikal.png
  tagline:
    en_us: "Lightweight CalDAV+CardDAV server."
  title:
    en_us: Baïkal
  port_map: "8001"
