name: opencloud
services:
  opencloud:
    image: opencloudeu/opencloud:latest
    container_name: opencloud
    # Command is removed so it starts the server normally
    environment:
      - OCIS_URL=http://192.168.68.120:9200
      - OCIS_INSECURE=true
    volumes:
      - /DATA/AppData/opencloud/config:/etc/ocis
      - /DATA/AppData/opencloud/data:/var/lib/ocis
    ports:
      - "9200:9200"
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "9200"
          description:
            en_us: "Web Interface"
      volumes:
        - container: /etc/ocis
          description:
            en_us: "Configuration"

x-casaos:
  architectures:
    - amd64
    - arm64
  main: opencloud
  author: OpenCloud Team
  category: Charlie
  title:
    en_us: OpenCloud
  port_map: "9200"
