name: omnitools
services:
  omnitools:
    image: iib0011/omni-tools:latest
    container_name: omnitools
    restart: unless-stopped
    ports:
      - 8678:80
    security_opt:
      - no-new-privileges:true

x-casaos:
  architectures:
    - amd64
    - arm64
  main: omnitools
  title:
    en_us: OmniTools
  tagline:
    en_us: A Swiss Army Knife of self-hosted web utilities.
  description:
    en_us: A collection of essential tools for everyday tasks, including PDF editing, image conversion, video trimming, and text formatting. Everything runs locally in your browser.
  developer: iib0011
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/omni-tools.png
  category: Charlie
  port_map: "8678"
