tname: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:next
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /DATA/AppData/uptime-kuma:/app/data
      # Mount the docker socket to monitor other containers on your ZimaOS
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3001:3001
    x-casaos:
      ports:
        - container: "3001"
          description:
            en_us: "Web Interface"
      volumes:
        - container: /app/data
          description:
            en_us: "Database and settings"

x-casaos:
  architectures:
    - amd64
    - arm64
  main: uptime-kuma
  author: louislam
  category: Charlie
  description:
    en_us: "A fancy self-hosted monitoring tool that tracks uptime for websites, services, and Docker containers."
  developer: Louis Lam
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/uptime-kuma.png
  tagline:
    en_us: "Self-hosted uptime monitoring."
  title:
    en_us: Uptime Kuma
  port_map: "3001"
