name: whoogle-search2
services:
  whoogle-search:
    container_name: whoogle
    image: benbusby/whoogle-search:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 5000
        published: "9005"
        protocol: tcp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: whoogle
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    deploy:
      resources:
        limits:
          memory: 8146374656
    labels:
      icon: https://i.ibb.co/M7MkCPQ/whoogle.png

x-casaos:
  architectures:
    - amd64
    - arm64
  main: whoogle-search
  title:
    en_us: Whoogle Search
  tagline:
    en_us: Privacy-respecting metasearch engine
  description:
    en_us: A self-hosted, ad-free, privacy-respecting metasearch engine.
  developer: Ben Busby
  icon: https://i.ibb.co/M7MkCPQ/whoogle.png
  category: Charlie
  port_map: "9005"
