name: whoogle-search
services:
  whoogle-search:
    container_name: whoogle-search
    image: benbusby/whoogle-search:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9005:5000
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: whoogle
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    deploy:
      resources:
        limits:
          memory: 8146374656
x-casaos:
  architectures:
    - amd64
    - arm64
  main: whoogle-search
  description:
    en_us: Whoogle - A self-hosted, ad-free, privacy-respecting metasearch engine
  tagline:
    en_us: Whoogle - A self-hosted, ad-free, privacy-respecting metasearch engine
  developer: Ben Busby
  icon: https://i.ibb.co/M7MkCPQ/whoogle.png
  thumbnail: ""
  title:
    en_us: Whoogle
  category: Charlie
  port_map: "9005"
