name: microbin
services:
  microbin:
    container_name: microbin
    image: danielszabo99/microbin:latest
    restart: unless-stopped
    ports:
      - 9010:8080
    environment:
      - MICROBIN_ADMIN_USERNAME=charlie
      - MICROBIN_ADMIN_PASSWORD=charlie
      - MICROBIN_EDITABLE=true
      - MICROBIN_HIGHLIGHTSYNTAX=true
      - MICROBIN_QR=true
      - MICROBIN_WIDE=true
    volumes:
      - /DATA/AppData/$AppID/data:/app/pasta_data

x-casaos:
  architectures:
    - amd64
    - arm64
  main: microbin
  title:
    en_us: MicroBin
  tagline:
    en_us: A tiny, self-hosted, feature-rich pastebin.
  description:
    en_us: MicroBin is a super tiny, configurable, self-contained pastebin web app. It supports file uploads, URL shortening, and syntax highlighting.
  developer: Daniel Szabo
  icon: https://microbin.eu/logo.png
  category: Charlie
  port_map: "9010"
