name: homebox
services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
      - TZ=$TZ
    volumes:
      - /DATA/AppData/$AppID/data:/data
    ports:
      - 3100:7745

x-casaos:
  architectures:
    - amd64
    - arm64
  main: homebox
  title:
    en_us: Homebox
  tagline:
    en_us: Inventory and organization system built for the home user.
  description:
    en_us: Homebox is the inventory management system focused on simplicity and ease of use. Track your tools, electronics, and household items with ease.
  developer: Hay-Kot
  icon: https://raw.githubusercontent.com/hay-kot/homebox/main/static/img/favicon.png
  category: Charlie
  port_map: "3100"
