name: whoogle-search
services:
  whoogle-search:
    cap_drop:
      - ALL
    cpu_shares: 90
    command: []
    container_name: whoogle
    deploy:
      resources:
        limits:
          memory: 8146374656
        reservations:
          devices: []
    image: benbusby/whoogle-search:latest
    labels:
      icon: https://i.ibb.co/M7MkCPQ/whoogle.png
    ports:
      - target: 5000
        published: "9005"
        protocol: tcp
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    user: whoogle
    volumes: []
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: Charlie
  category: charlie
  hostname: ""
  icon: https://i.ibb.co/M7MkCPQ/whoogle.png
  index: /
  is_uncontrolled: false
  port_map: "9005"
  scheme: http
  store_app_id: whoogle-search
  title:
    custom: ""
    en_gb: whoogle-search
