name: anchor
services:
  anchor:
    image: ghcr.io/zhfahim/anchor:latest
    container_name: anchor
    restart: unless-stopped
    ports:
      - "2997:3000"
    volumes:
      - /DATA/AppData/anchor/data:/data
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC # Change to your timezone
      - USER_SIGNUP=enabled # Change to disabled to turn off signups
    x-casaos:
      ports:
        - container: "2997"
          description:
            en_us: "Web Interface"
      volumes:
        - container: /data
          description:
            en_us: "App Data & Notes"

x-casaos:
  architectures:
    - amd64
    - arm64
  main: anchor
  author: zhfahim
  category: Charlie
  description:
    en_us: "An offline-first, self-hostable note-taking application focused on speed, privacy, and simplicity. A great alternative to Google Keep."
  developer: ZhFahim
  icon: https://raw.githubusercontent.com/zhfahim/anchor/main/web/public/icons/anchor_icon.png
  tagline:
    en_us: "Fast, private, mobile-first notes."
  title:
    en_us: Anchor Notes
  port_map: "2997"
